#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make dummy 0 directory
mkdir 0

runApplication blockMesh
cp system/decomposeParDict.hierarchical system/decomposeParDict
runApplication decomposePar

cp system/decomposeParDict.ptscotch system/decomposeParDict
nProc=$(getNumberOfProcessors)
runParallel snappyHexMesh $nProc -overwrite

find . -type f -iname "*level*" -exec rm {} \;

ls -d processor* | xargs -i cp -r 0.org ./{}/0 $1

runParallel topoSet $nProc
runParallel `getApplication` $nProc

runApplication reconstructParMesh -constant
runApplication reconstructPar

# Copy initial conditions
rm -rf 0
cp -rf 0.org 0

rm -rf processor*

topoSet
runApplication vorticity
runApplication R

./gensampledict
runApplication sample -latestTime
mv log.sample log.sample.contours
runApplication sample -latestTime -dict system/sampleDict.streamwise

# ----------------------------------------------------------------- end-of-file
