#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make dummy 0 directory
mkdir 0

runApplication blockMesh
runApplication snappyHexMesh -overwrite

rm -rf 0
cp -rf 0.org 0

#runApplication extrudeMesh
runApplication topoSet
runApplication simpleFoam
runApplication sample

# ----------------------------------------------------------------- end-of-file
