#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite

cp -rf 0.org 0

runApplication topoSet
runApplication extrudeMesh
runApplication `getApplication`

#runApplication uprime
#runApplication sample

# ----------------------------------------------------------------- end-of-file
